name: render
on:
  push:
    branches: main
permissions:
  contents: write
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      # Checkout this repo
      - uses: actions/checkout@v4

      # Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install R packages
      - uses: r-lib/actions/setup-r-dependencies@v2

      # Install pandoc
      - uses: r-lib/actions/setup-pandoc@v2

      # Render the qmd file
      - name: Render Quarto Slides
        shell: Rscript {0}
        run: quarto::quarto_render("index.qmd")

      # Publish to GitHub pages
      - name: Publish to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: .
